### ISSUE TITLE
get_new_data is very slow

### ISSUE THREAD

**Issue by cizhenshi** [GothicAi/Instaboost#10]
I use get_new_data to genrate image. but for a 1300X2600 image, it takse 7 seconds. Is this normal?

**Comment by Fang-Haoshu** [comment]
Hi, it's normal. 1, the size of the image is pretty large; 2. we need to parallelize the image processing, that's why we wrap it as a dataloader.

**Comment by Fang-Haoshu** [comment]
I guess you need more workers when loading the data.
