### ISSUE TITLE
Installation on 64 bit ARM platform

### ISSUE THREAD

**Issue by marsbars33** [GothicAi/Instaboost#13]
I am attempting to install Instaboost on a platform with aarch64 (anaconda is unavailable for this architecture, NVIDIA Linux 4 Tegra 32.2.1 running Ubuntu 18.04).

I successfully installed OpenCV 2.4.13 and opencv-mat in a virtual environment, following the provided instructions.

However, it appears the opencv install did not include opencv-python, despite having set BUILD_opencv_python=ON. I don't see a version of opencv-python matching 2.14 available in the release history on pypi. Does the version of opencv-python have to also be 2.14? Is there a different parameter I should be setting in CMakeLists when I install opencv-2.4.13? Would appreciate any help you can provide.

Thank you in advance!

**Comment by Fang-Haoshu** [comment]
Hi, you can install instaboostfast instead :D

**Comment by Fang-Haoshu** [comment]
The Easy install version in the readme is much easier to install
