### ISSUE TITLE
Instaboostfast Inpainting

### ISSUE THREAD

**Issue by marsbars33** [GothicAi/Instaboost#14]
Hello!
I successfully installed Instaboostfast and am experimenting with augmenting my data. Is there a simple way to improve the inpainted background?

Pre-aug:
![](https://user-images.githubusercontent.com/55502615/68774261-d31bd180-05fa-11ea-9cfa-ad096161d552.jpg)
Post-aug:
![image](https://user-images.githubusercontent.com/55502615/68773948-643e7880-05fa-11ea-98d9-d9496e998875.png)
Pre-aug:
![CA_004](https://user-images.githubusercontent.com/55502615/68774327-ef1f7300-05fa-11ea-9cd4-29d9e968fc01.jpg)
Post-aug:
![image](https://user-images.githubusercontent.com/55502615/68773968-6a345980-05fa-11ea-9085-60e655ffc065.png)

Thank you in advance :)

**Comment by Fang-Haoshu** [comment]
Hi! I think you might try some inpaiting method using deep learning

**Comment by Fang-Haoshu** [comment]
Hi! May I know what dataset it is? We are recently trying instaboost on different datasets:D @marsbars33
