### ISSUE TITLE
Puzzed about the reported AP in your paper: which codebase do you use in different tables?

### ISSUE THREAD

**Issue by XCRobert** [GothicAi/Instaboost#17]
In table 1
![image](https://user-images.githubusercontent.com/16361120/71559132-936b5500-2a95-11ea-8011-1368ebb624f1.png)
Maskrcnn (res50-fpn) is 37.6 which is same as perfomance in https://github.com/roytseng-tw/Detectron.pytorch/blob/master/BENCHMARK.md.
This is COCO val2017 results rather than test-dev results? Are you confused with this two eval sets?

In table 5
![image](https://user-images.githubusercontent.com/16361120/71559199-679c9f00-2a96-11ea-8a02-f1fff2c3024e.png)
The result of maskrcnn (res50-fpn) becomes 38.2 . 
I am lost in these.  Which codebase do you use in different tables and different rows in a table?

**Comment by rogerwwww** [comment]
Hi, 

Results in Table 1 are obtained in our own experiment running the code provided by Detectron.pytorch. The results are neither the same as [Detectron.pytorch's benchmark](https://github.com/roytseng-tw/Detectron.pytorch/blob/master/BENCHMARK.md), if you look at AP50, AP75, etc.

In Table 5, these results are on the backbone res101-fpn. They are consistent with Table 1 & 2.

**Comment by XCRobert** [comment]
Thanks for your patient reply! It is a good work. Do this paper have the newest bibtex for now? Its bibtex still directs to Arxiv rather  than ICCV2019. We want to cite your work.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your suggestion! We have updated the readme.

Bests

**Comment by GothicAi** [comment]
Hi, we have updated the bibtex [here](https://github.com/GothicAi/Instaboost#citation). Thank you for your recognition of our work.
