### ISSUE TITLE
Can this method be used for pure object detection? 

### ISSUE THREAD

**Issue by bruceyang2012** [GothicAi/Instaboost#3]
If there is no annotation of instances, can this method be used for pure object detection? If so, how can I change the code? I am using mmdetection with PASCAL VOC dataset now，thanks.

**Comment by Fang-Haoshu** [comment]
Hi! Currently we need instance mask for data augmentation. Thanks!

**Comment by weixianghong** [comment]
> Hi! Currently we need instance mask for data augmentation. Thanks!

Is your method applicable to panoptic segmentation?

**Comment by Fang-Haoshu** [comment]
Hi, currently no, but we are looking into that and hope we can achieve it in the future,
