### ISSUE TITLE
run time too long

### ISSUE THREAD

**Issue by universea** [GothicAi/Instaboost#5]
one picture cost 1s on average..
preprocess =  0.04111599922180176
instaboost =  0.9120709896087646
preprocess =  0.023632526397705078
instaboost =  0.2705254554748535
instaboost =  1.2194056510925293
preprocess =  0.030213356018066406
preprocess =  0.031014442443847656
instaboost =  0.5391912460327148
preprocess =  0.009119987487792969
instaboost =  0.7795922756195068
preprocess =  0.08683609962463379
instaboost =  0.9073679447174072
instaboost =  1.1515531539916992
preprocess =  0.011395692825317383
preprocess =  0.12354302406311035
instaboost =  0.8408169746398926
preprocess =  0.010410070419311523
instaboost =  0.668351411819458
preprocess =  0.0333857536315918
instaboost =  0.7038695812225342
instaboost =  1.3578264713287354
preprocess =  0.12049746513366699
preprocess =  0.13341665267944336
instaboost =  1.4019551277160645
preprocess =  0.013040304183959961
instaboost =  1.5061841011047363
preprocess =  0.0871119499206543
instaboost =  1.1349220275878906
instaboost =  0.4259028434753418
preprocess =  0.10847687721252441
preprocess =  0.11221194267272949
instaboost =  0.9127352237701416
preprocess =  0.02018260955810547
instaboost =  0.5885348320007324
instaboost =  0.7217702865600586
preprocess =  0.025765180587768555
preprocess =  0.032164812088012695
instaboost =  1.0032260417938232
preprocess =  0.017023086547851562

**Comment by Fang-Haoshu** [comment]
Hi, can you tell us your machine configuration? Instaboost need parallel processing using multiple CPUs

**Comment by universea** [comment]
ubuntu18.04 
Memory 31.1GB
Intel Core i7-7800X CPU 3.5GHz X 12
1080ti

**Comment by Fang-Haoshu** [comment]
Thanks, I guess it shouldn't be that slow. Can you tell us more detail? Like what framework you are training, how many workers, etc.

**Comment by universea** [comment]
I use it on the ssd-mobilenetv3 , the framework is paddlepaddle, cpu num_workers is 6

**Comment by Fang-Haoshu** [comment]
I guess we need more workers. Perhaps you can try 20 or 40
