### ISSUE TITLE
Undefined names: Missing imports?

### ISSUE THREAD

**Issue by cclauss** [GothicAi/Instaboost#6]
[flake8](http://flake8.pycqa.org) testing of https://github.com/GothicAi/Instaboost on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./yolact/layers/output_utils.py:59:17: F821 undefined name 'center_size'
        boxes = center_size(boxes)
                ^
./yolact/layers/modules/multibox_loss.py:383:26: F821 undefined name 'sanitize_coordinates'
                x1, x2 = sanitize_coordinates(pos_bboxes[:, 0], pos_bboxes[:, 2], img_width)
                         ^
./yolact/layers/modules/multibox_loss.py:384:26: F821 undefined name 'sanitize_coordinates'
                y1, y2 = sanitize_coordinates(pos_bboxes[:, 1], pos_bboxes[:, 3], img_height)
                         ^
3     F821 undefined name 'sanitize_coordinates'
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by rogerwwww** [comment]
Hi @GouMinghao, could you please check this on yolact?

**Comment by GouMinghao** [comment]
Hi, `center_size` is defined in ./yolact/layers/box_utils.py line 21.
`sanitize_coordinates` is defined in ./yolact/layers/box_utils.py line 284.

**Comment by cclauss** [comment]
Then we need something like __from box_utils import center_size__ and __from box_utils import sanitize_coordinates__.

**Comment by GouMinghao** [comment]
`sanitize_coordinates` is imported in line 13.
You can look at [yolact issue#51](https://github.com/dbolya/yolact/issues/51) for details about the problem with `center_size` .

**Comment by Fang-Haoshu** [comment]
Thanks @cclauss ! It seems that it's a dead path. We will update the codes once yolact is updated.
