### ISSUE TITLE
What is best InstaboostConfig for COCO dataset?

### ISSUE THREAD

**Issue by poodarchu** [GothicAi/Instaboost#7]

**Comment by GothicAi** [comment]
Hi! We recommend to use the default config for coco dataset. In fact, it is hard to say what is best, because the performance depends on both the strength of data augmentation and the epochs you trained your net.

**Comment by Fang-Haoshu** [comment]
I guess you can simply use the default config by cfg = InstaBoostConfig()

**Comment by poodarchu** [comment]
> Hi! We recommend to use the default config for coco dataset. In fact, it is hard to say what is best, because the performance depends on both the strength of data augmentation and the epochs you trained your net.

I mean what is the best config on coco dataset mentioned in your paper?

**Comment by Fang-Haoshu** [comment]
Oh I see, for the best config, you can try action_candidate: tuple = ('normal', 'horizontal', 'skip'),   action_prob: tuple = (1, 0, 0), scale: tuple = (0.8, 1.2), dx: float = 15, dy: float = 15,  theta=(-1, 1), color_prob=0.5, heatmap_flag=True @poodarchu
